// Mock data
export const allProducts = [
  {
    id: "1",
    name: "Vintage Leather Bag",
    originalPrice: 150.0,
    salePrice: null,
    tag: null,
    category: "Apparel",
    brand: "Timeless",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Leather+Bag",
  },
  {
    id: "2",
    name: "Wireless Headphones",
    originalPrice: 99.99,
    salePrice: 71.99,
    tag: "-50%",
    category: "Electronics",
    brand: "AudioPlus",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Headphones",
  },
  {
    id: "3",
    name: "Smart Watch X-1",
    originalPrice: 299.5,
    salePrice: null,
    tag: null,
    category: "Electronics",
    brand: "TechGear",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Smart+Watch",
  },
  {
    id: "4",
    name: "Classic Denim Jacket",
    originalPrice: 75.0,
    salePrice: null,
    tag: null,
    category: "Apparel",
    brand: "RebelWear",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Denim+Jacket",
  },
  {
    id: "5",
    name: "Running Shoes Pro",
    originalPrice: 120.0,
    salePrice: null,
    tag: "Special",
    category: "Footwear",
    brand: "RunFast",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Running+Shoes",
  },
  {
    id: "6",
    name: "Handcrafted Wooden Chair",
    originalPrice: 450.0,
    salePrice: null,
    tag: null,
    category: "Home Goods",
    brand: "Woodworks",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Wooden+Chair",
  },
  {
    id: "7",
    name: "Espresso Machine 3000",
    originalPrice: 350.0,
    salePrice: null,
    tag: null,
    category: "Home Goods",
    brand: "BrewMaster",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Espresso+Machine",
  },
  {
    id: "8",
    name: "Digital Camera D-SLR",
    originalPrice: 800.0,
    salePrice: null,
    tag: null,
    category: "Electronics",
    brand: "PhotoPro",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Digital+Camera",
  },
  {
    id: "9",
    name: "Designer T-Shirt",
    originalPrice: 45.0,
    salePrice: 30.0,
    tag: "-50%",
    category: "Apparel",
    brand: "UrbanStyle",
    image: "https://placehold.co/400x300/E5E7EB/1F2937?text=Designer+T-shirt",
  },
];

export const mockCategories = [
  "All",
  "Electronics",
  "Apparel",
  "Footwear",
  "Home Goods",
];
export const mockBrands = [
  "All",
  "AudioPlus",
  "TechGear",
  "RebelWear",
  "RunFast",
  "Woodworks",
  "BrewMaster",
  "PhotoPro",
  "UrbanStyle",
  "Timeless",
];
export const mockColors = ["All", "Blue", "White", "Black", "Silver"];
